name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x 15.x 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.15.1
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: development
        BRANCH: master
        FOLDER: dist/Weather-App
        BUILD_SCRIPT: npm install && npm run build -- --prod
